name: Pull Request - Closed

# use the same concurrency group as pull-request.yml
# to force Closed to run after currently running actions are finished
concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    types: [closed]

permissions:
  actions: read
  pull-requests: read

jobs:
  cleanup:
    name: Cleanup
    uses: ./.github/workflows/reusable-cleanup.yml
    secrets: inherit
